wip: use dag to publish staging packages
Signed-off-by: Jason Hall <jason@chainguard.dev>

diff --git a/.github/workflows/dag-push-staging.yaml b/.github/workflows/dag-push-staging.yaml
--- a/.github/workflows/dag-push-staging.yaml
+++ b/.github/workflows/dag-push-staging.yaml
@@ -32,11 +32,9 @@ jobs:
       - uses: actions/checkout@v3
         with:
           repository: wolfi-dev/dag
-          path: ./dag
-      - working-directory: ./dag
+          path: ${{github.workspace}}/dag
+      - working-directory: ${{github.workspace}}/dag
         run: go install
-
-      - uses: actions/checkout@v3
 
       - uses: google-github-actions/auth@v0
         with:
@@ -45,38 +43,87 @@ jobs:
       - uses: google-github-actions/setup-gcloud@v0
         with:
           project_id: ${{env.PROJECT}}
+      - run: gcloud auth configure-docker --quiet
 
       - name: Setup Build Cluster
-        working-directory: ./dag
+        working-directory: ${{github.workspace}}/dag
         run: |
-          gcloud container clusters create ${CLUSTER_NAME} \
-            --zone            ${CLUSTER_ZONE}  \
+          # Get our current public IP
+          me=$(printf "%s/32" "$(curl -s https://api.ipify.org)")
+
+          gcloud container clusters create "${CLUSTER_NAME}" \
+            --enable-ip-alias \
+            --network                       projects/staging-shared-7864/global/networks/staging-shared-a6474a3 \
+            --subnetwork                    projects/staging-shared-7864/regions/us-central1/subnetworks/staging-shared-imgs-us-c1-209d340 \
+            --cluster-secondary-range-name  gke-a-pods \
+            --services-secondary-range-name gke-a-svcs \
+            --tags                          "egress-inet" \
+            --enable-dataplane-v2 \
+            --enable-intra-node-visibility \
+            --enable-master-authorized-networks \
+            --master-authorized-networks="${me}" \
+            --service-account staging-images-ci@staging-images-183e.iam.gserviceaccount.com \
+            --zone            "${CLUSTER_ZONE}" \
             --release-channel rapid \
             --workload-pool   "${PROJECT}.svc.id.goog" \
             --machine-type    e2-standard-32 \
             --num-nodes       1
 
           gcloud container node-pools create arm-nodes \
-            --cluster        ${CLUSTER_NAME} \
-            --zone           ${CLUSTER_ZONE} \
+            --cluster        "${CLUSTER_NAME}" \
+            --zone           "${CLUSTER_ZONE}" \
+            --tags           "egress-inet" \
+            --service-account staging-images-ci@staging-images-183e.iam.gserviceaccount.com \
             --machine-type   t2a-standard-32 \
             --num-nodes      1
 
-          ./scripts/setup-cluster.sh
+          ./scripts/setup-cluster.sh staging-images-ci
+
+      - uses: 'google-github-actions/get-gke-credentials@v0'
+        with:
+          cluster_name: ${{ env.CLUSTER_NAME }}
+          location: ${{ env.CLUSTER_ZONE }}
+
+      - uses: actions/checkout@v3
+        with:
+          repository: wolfi-dev/bootstrap-stage1
+          path: ${{github.workspace}}/bootstrap-stage1
 
       # NB: These publish to a separate path in the staging bucket until they're ready.
-      - run: |
+      - working-directory: ${{github.workspace}}/bootstrap-stage1
+        run: |
           dag pod \
             --cpu=30 --ram=100Gi \
             --bucket=wolfi-dag-test-bucket/dag-test/bootstrap/stage1 \
             --secret-key
-      - run: |
+      - working-directory: ${{github.workspace}}/bootstrap-stage1
+        run: |
           dag pod \
             --cpu=30 --ram=100Gi \
             --bucket=wolfi-dag-test-bucket/dag-test/bootstrap/stage1 \
             --secret-key \
             --arch=arm64
 
+      - name: Collect diagnostics
+        if: ${{ failure() }}
+        run: |
+          resources="pods daemonsets serviceaccounts namespaces"
+          for ns in $(kubectl get ns -oname | cut -d'/' -f 2); do
+            for resource in ${resources}; do
+              echo --- $ns $resource ---
+              kubectl get $resource -n${ns}
+              for x in $(kubectl get $resource -n${ns} -oname || true); do
+                echo "::group:: describe $resource $x"
+                # Don't fail if the resource disappears midway.
+                kubectl describe -n${ns} $x || true
+                echo '::endgroup::'
+              done
+            done
+          done
+
       - name: Teardown Build Cluster
         if: ${{ always() }}
-        run: gcloud container clusters delete tmp-cluster --location=${CLUSTER_ZONE}
+        run: |
+          gcloud container clusters delete "${CLUSTER_NAME}" \
+            --zone "${CLUSTER_ZONE}" \
+            --quiet
